version: '3.3'
services:
    php:
        container_name: dockyard
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: 'app'
        ports:
            - 80:80
        volumes:
            - .:/var/www/html
            - .:/app:delegated
            - ~/.composer:/home/root/.composer:delegated  

    db:
        container_name: db
        image: mysql
        command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
        restart: always

        environment:
            MYSQL_ROOT_USERNAME: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_DATABASE: dockyard

        volumes:
            - .docker/db/init.sql:/data/application/init.sql
        



    adminer:
        container_name: admin
        image: adminer
        restart: always
        ports:
             - 81:8080


